### ISSUE TITLE
몽고디비주소 환경변수로 변경하기

### ISSUE THREAD

**Issue by thdwngus2** [AndrewDongminYoo/myproject#45]

**Comment by woodstock1993** [comment]
동민님 블로그 참고
https://cat-minzzi.tistory.com/52

**Comment by AndrewDongminYoo** [comment]
커맨드라인에서도 해결할 수 있다.

bash/ubuntu의 경우 export 키=값 (이퀄기호사용)
window cmd 의 경우 setx 키 값 (띄어쓰기임)
powershell 의 경우 $Env:키="값" (쌍따옴표 사용)
