### ISSUE TITLE
index.html에 og 관련 메타태그 추가하기

### ISSUE THREAD

**Issue by woodstock1993** [AndrewDongminYoo/myproject#47]
SNS에 공유되어질 때 나타날 이미지, 제목, 내용 등을 표시해 주기 위한 부분 작업

**Comment by woodstock1993** [comment]
SNS 공유시 그림이 뜨지 않는 것 같다.
og:description 부분이 아직 반영이 안돼서 그런지 default 값이 들어갔다. '여기를 눌러 링크를 확인하세요'

**Comment by woodstock1993** [comment]
<meta property="og:author" content="jaryogoojo">
    <meta property="og:title" content="오늘 뭐 먹지?">
    <meta property="og:url" content="https://itwassummer.shop/">
    <meta property="og:description" content="퇴근 전에 슬쩍 배달 맛집 탐방하기!! 날씨와 기분에 맞춰 꺼내먹어요">
    <meta property="og:image" content="https://itwassummer.shop/static/image/roulette.webp">

author부분 url 부분 그리고 image까 안떠서 https로 변경해서 추가해보았습니다. 이미 같은 경우는 될지는...

**Comment by AndrewDongminYoo** [comment]
https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fitwassummer.shop%2F

### 해결해야 하는 경고 
**추정된 속성** 
'og:image' 속성은 다른 태그에서 추정할 수 있는 값이더라도 명확하게 입력해야 합니다. 
**자산 누락됨** 
다음 필수 자산이 누락되었습니다: og:url, og:type, fb:app_id 
**'속성' 대신 '이름'으로 지정된 태그** 
다음 메타 태그는 'property' 대신 'name'을 사용하여 지정되었으며 '속성' 키를 사용하여 지정되지 않는 한 무시됩니다: og:title, og:description, og:image

property가 아닌 name으로 지정해주어야 합니다!! 페이스북에서 제공하는 오픈그래프 공유디버거를 활용했습니다.

**Comment by woodstock1993** [comment]
local 브랜치 파서 'SJH' 브런치에 push했습니다. 됐으면...
